// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5IiXPY4b7-Xa8vuzjVjia-RwCzacDDx4',
    appId: '1:726979794843:web:30f8f204003a33ff8bb33e',
    messagingSenderId: '726979794843',
    projectId: 'product-hub-708ff',
    authDomain: 'product-hub-708ff.firebaseapp.com',
    storageBucket: 'product-hub-708ff.firebasestorage.app',
    measurementId: 'G-HL4RFNFXVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjO7V8c-0I9ZF4BIt8JdzUpUH5xoDkWUg',
    appId: '1:726979794843:android:0dc00aee8dfc7d8f8bb33e',
    messagingSenderId: '726979794843',
    projectId: 'product-hub-708ff',
    storageBucket: 'product-hub-708ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCghi7DjGDufQ0rl5MKHSzCo55PhbAuK4',
    appId: '1:726979794843:ios:e234fe38b168aa738bb33e',
    messagingSenderId: '726979794843',
    projectId: 'product-hub-708ff',
    storageBucket: 'product-hub-708ff.firebasestorage.app',
    iosBundleId: 'com.example.productHub',
  );
}
